# Generated by Django 4.1.13 on 2024-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_alter_package_matching_state_alter_package_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplealias',
            options={'verbose_name_plural': 'sample aliases'},
        ),
        migrations.AlterModelOptions(
            name='sequencingdatahash',
            options={'verbose_name_plural': 'sequencing data hashes'},
        ),
        migrations.AlterField(
            model_name='sequencingdata',
            name='s3_storage_class',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('DEEP_ARCHIVE', 'Deep Archive'), ('', 'Empty')], default='STANDARD', max_length=50, null=True),
        ),
    ]
