# Generated by Django 4.1.13 on 2024-12-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0011_alter_samplealias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='origin',
            field=models.CharField(blank=True, choices=[('None', 'Unset'), ('NCBI', 'Ncbi'), ('TbKb', 'Tbkb'), ('Admin', 'Admin')], default='TbKb', max_length=128, null=True),
        ),
    ]
