# Generated by Django 4.1.13 on 2024-12-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_alter_sample_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequencingdata',
            name='data_location',
            field=models.CharField(choices=[('NCBI', 'Ncbi'), ('TB-Kb', 'Tbkb'), ('CNCB', 'Cncb')], max_length=8192),
        ),
    ]
