# Generated by Django 4.2.17 on 2025-01-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0013_alter_sequencingdata_data_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
