# Generated by Django 4.2.18 on 2025-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0014_attachment_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genotyperesistance",
            name="version",
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name="sample",
            name="origin",
            field=models.CharField(
                blank=True,
                choices=[("None", "Unset"), ("NCBI", "Ncbi"), ("TbKb", "Tbkb"), ("Admin", "Admin")],
                db_index=True,
                default="TbKb",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="samplealias",
            name="origin",
            field=models.CharField(
                choices=[("SRS", "Srs"), ("BioSample", "Biosample"), ("TBKB", "Tbkb")],
                db_index=True,
                default="TBKB",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="genotyperesistance",
            index=models.Index(fields=["sample", "drug"], name="submission__sample__31cca0_idx"),
        ),
        migrations.AddIndex(
            model_name="genotyperesistance",
            index=models.Index(fields=["version", "drug_id"], name="idx_version_drug_id"),
        ),
    ]
