# Generated by Django 4.2.18 on 2025-02-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0015_alter_genotyperesistance_version_alter_sample_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplealias',
            name='origin_label',
            field=models.CharField(db_index=True, default='', max_length=1024),
        ),
    ]
