# Generated by Django 4.2.18 on 2025-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0016_alter_samplealias_origin_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplealias",
            name="name",
            field=models.CharField(db_index=True, max_length=2048),
        ),
    ]
