from django.core.management.base import BaseCommand
from django.db import transaction

from submission.models import GenotypeResistance, Sample, SampleAlias


class Command(BaseCommand):
    """Remove test data generated by generate_genotype_resistance command."""

    help = "Remove test data (samples, aliases, and genotype resistances)"

    def handle(self, *args, **options):
        """Handle the command."""
        with transaction.atomic():
            # Remove GenotypeResistance entries with test variants
            genotype_count = GenotypeResistance.objects.filter(variant__startswith="test").delete()[
                0
            ]

            # Remove SampleAlias entries with test names
            alias_count = SampleAlias.objects.filter(name__startswith="test").delete()[0]

            # Remove Sample entries with test isolation source
            sample_count = Sample.objects.filter(isolation_source="test").delete()[0]

        self.stdout.write(
            f"Removed:\n"
            f"- {sample_count} test Samples\n"
            f"- {alias_count} test Sample Aliases\n"
            f"- {genotype_count} test Genotype Resistances",
        )
