# Generated by Django 4.1.13 on 2025-01-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genphen', '0012_alter_variantgrade_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDSTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('category', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdst_categories', to='genphen.drug')),
                ('medium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='genphen.growthmedium')),
                ('method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='genphen.pdsassessmentmethod')),
            ],
        ),
    ]
