# Generated by Django 4.2.18 on 2025-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genphen", "0013_pdstestcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdstestcategory",
            options={"verbose_name_plural": "PDS Test Categories"},
        ),
        migrations.AlterField(
            model_name="drug",
            name="drug_id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
