# Generated by Django 4.1.13 on 2025-01-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genphen', '0013_pdstestcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdstestcategory',
            options={'verbose_name_plural': 'PDS Test Categories'},
        ),
        migrations.CreateModel(
            name='VariantAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('alternative_nucleotide', models.CharField(max_length=200, null=True)),
                ('reference_nucleotide', models.CharField(max_length=200, null=True)),
                ('v1_annotation', models.TextField()),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='v1_annotations', to='genphen.variant')),
            ],
        ),
    ]
