# Generated by Django 4.2.18 on 2025-01-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genphen", "0014_alter_pdstestcategory_options_variantadditionalinfo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pdstestcategory",
            options={"verbose_name_plural": "PDS Test Categories"},
        ),
    ]
